services:
  ubuntu_dev:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: ubuntu_lustre_dev
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules  # Use host kernel modules
      - /usr/src:/usr/src  # Use host kernel source
      - .:/workspace  # Mount current directory
    stdin_open: true  # Interactive mode
    tty: true  # Keep terminal connection