#!/bin/bash
# lustreenv

if [[ $# -eq 0 ]]; then
  echo "Usage: . ./lustreenv <root_project_directory>"
  return 1
fi

# Set LUSTRE_HOME
LUSTRE_HOME=$1
if [[ ! -d "$LUSTRE_HOME" ]]; then
  echo "Error: Directory $LUSTRE_HOME does not exist."
  return 1
fi

export LUSTRE_HOME

# Set enviroment valiables
USER=$(whoami)
GROUP=$(id -gn)
ALIAS_FILE="$LUSTRE_HOME/aliases"
NVME_UTILS_DIR="$LUSTRE_HOME/nvme-utils"

# Set aliases
if [[ -f "$ALIAS_FILE" ]]; then
source "$ALIAS_FILE"
  echo "Aliases loaded from $ALIAS_FILE"
else
  echo "Alias file $ALIAS_FILE not found"
fi

_lustre_setup_completion() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local cmds="setup_mgt_mdt setup_ost start_mgs start_mds start_oss stop_mgs stop_mds stop_oss status check remove_pools"
    COMPREPLY=( $(compgen -W "${cmds}" -- "${cur}") )
    return 0
}

complete -F _lustre_setup_completion lustre-setup